version: 2.22.0
services:
    fe-mvr:
        container_name: fe-mvr
        image: node:lts-alpine
        ports:
            - 3000:3000
        volumes:
            - ./frontend:/app
        working_dir: /app
        deploy:
            resources:
                limits:
                    cpus: '1.5'
                    memory: 700M
        entrypoint: yarn dev
    be-mvr:
        container_name: be-mvr
        image: 8.2-fpm-alpine
        build: ./backend
        ports:
            - 8000:8000
        volumes:
            - ./backend:/app
        working_dir: /app
        deploy:
            resources:
                limits:
                    cpus: '.5'
                    memory: 500M
        depends_on:
            - db-mvr
        entrypoint: php artisan serve --host 0.0.0.0
    db-mvr:
        image: mysql
        container_name: db-mvr
        # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
        # (this is just an example, not intended to be a production configuration)
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mvr_app
        ports:
            - 3306:3306
    pma-mvr:
        image: phpmyadmin
        container_name: pma-mvr
        # restart: always
        ports:
            - 8001:80
        environment:
            - PMA_ARBITRARY=1
        depends_on:
            - db-mvr
